# Question 1
Write a Python program which will take N names from the user. Create a dictionary from the N names that will hold First_name, Middle_name and Last_name in separate keys. The inputs will take N at first and then take N names. You can assume that the names will contain less than or equal 3 words and there will be single space between each part of the name.

Sample Input: 

4

Zubayer Ahmed

Sadia Nur Amin

Mehedi Hasan Shawon

Nafis

Sample Output:
{ "Fname" : [“Zubayer”, “Sadia”, “Mehedi”, “Nafis”] , "Mname" : [“Nur”, “Hasan”], "Lname" : [“Ahmed”, “Amin”, “Shawon”] }

In [4]:
num = int(input('enter number of students : '))
Fname_list = []
Mname_list = []
Lname_list = []
name_list = []
for item in range(0,num) :
    names = input("enter student's names :")
    names_list = names.split (' ')
    if len(names_list) == 1 : 
            Fname_list.append(names_list[0])
    if len(names_list) == 2 : 
        if names_list[0] not in Fname_list :
            Fname_list.append(names_list[0])
        if names_list[1] not in Lname_list :
            Lname_list.append(names_list[1])
    if len(names_list) == 3 : 
        if names_list[0] not in Fname_list :
            Fname_list.append(names_list[0])
        if names_list[1] not in Mname_list :
            Mname_list.append(names_list[1])
        if names_list[2] not in Lname_list :
            Lname_list.append(names_list[2])
    names_dict = {"Fname":Fname_list,"Mname":Mname_list,"Lname":Lname_list}
print (names_dict)

enter number of students : 2
enter student's names :Mifta
enter student's names :Anika Islam
{'Fname': ['Mifta', 'Anika'], 'Mname': [], 'Lname': ['', 'Islam']}

# Question 2
 One of the important tasks in computational biology is to find short repeating patterns from DNA sequences. These patterns help the biologists to analyze the functionality of different parts in a living being. As a computer science student, you are asked to write a program that will find all the patterns of a given length from a DNA sequence and their number of presence in that sequence. This information will help to find the dominant pattern of a given length in the sequence. You will also find the dominant pattern. Dominant pattern is the sequence which has maximum occurrence. If there are multiple dominant pattern the program will print “No Dominant Pattern found.” 
 

Sample Input: 

ATTCGATCG

3 

Sample Output: 

ATT 1

TTC 1

TCG 2

CGA 1

GAT 1

ATC 1

Dominant Pattern: TCG

In [2]:
# task 2
code = input('enter the code : ')
count = 0 
code_dict = {}
maxim = -999999
value_list = []
for i in range(0,len(code)) :
    div_code = code[i:i+3]
    if len(div_code) == 3 :
        if div_code not in code_dict :
            code_dict[div_code] = 1
        else :
            code_dict[div_code] += 1
for key1,value1 in code_dict.items() :
    print (key1,value1)
    if value1 > maxim :
        maxim = value1 
        for key2,value2 in code_dict.items() :
            if maxim == value2 :
                maxim_key = key2 
print ('Dominant Pattern:',maxim_key)

enter the code : ATTCGATCG
ATT 1
TTC 1
TCG 2
CGA 1
GAT 1
ATC 1
Dominant Pattern: TCG

# Question 3
Counter Strike Global Offensive is a first person shooting(FPS) game where in a match 2 teams each with 5 members play against each other in different maps. Let's say there are 2 teams, Team A and Team B. For the first half (15 rounds) Team A will play as terrorists and Team B members will play as counter terrorists. In the second half(15 rounds) Team B will play as terrorists and Team A will play as counter terrorists. The first team to reach 16 rounds will win the match. In order for the terrorist team to win a round they have to plant, defend and explode a bomb at a particular spot or eliminate all the members of the counter terrorist team. In order for the counter terrorist team to win a round, they have to eliminate all the members of the terrorist team or diffuse the bomb that was planted by the terrorist team. Unlike other games, the Most Valuable Player(MVP), can be from any of the two teams regardless of which team wins based on the points calculated from performance of the players. Now you will be given the status of a match between 2 teams as input that will contain performance(Kill, Death, Assist, Bomb Plant, Bomb Defuse, Teammate kill)  of all 10 players of the 2 participating teams. Each performance category contains points based on following criteria:

2 points for a bomb plant.

2 points for a kill.

1 point for an assist.

3 points for defusing a bomb.

-1 point for killing a teammate.

Now your task is to find the top 3 players based on the total point. For simplicity, you can consider  that no 2 players will have the same point.


Input format: 


Team Name

Player Name

Kills

Deaths

Assists

Bomb Plant

Bomb Defuse

Teammate Kills


Sample Input:

NaVi flamie 23 13 3 2 2 0 

Fnatic Xizt 15 20 3 2 0 2	

Fnatic KRIMZ 12 23 9 2 2 1

Navi electronic 24 13 5 2 2 0	

Navi Zeus 14 22 12 2 2 0	

Navi Edward 20 18 8 1 1 1

Fnatic JW 13 24 5 3 0 0	

Navi s1mple 26 13 6 3 2 1

Fnatic twist 25 20 4 2 3 2

Fnatic Brollan 14 20 3 2 1 0 

Sample Output:

First: s1mple

Second: twist

Third: electronic

In [9]:
num = int(input())
NaVi_dict = {}
Fnatic_dict = {}
value_list = []
name_list = []
for i in range(0,num) :
    info = input('enter team member informations : ')
    info_list = info.split(' ')
    for j in range(0,len(info_list)) :
        if info_list[0] == 'NaVi' :
            summ1 = (int(info_list[2])*2) + int(info_list[3])  + (int(info_list[5])*2) + (int(info_list[6])*3) + (int(info_list[7])*(-1))
            if summ1 not in NaVi_dict :
                NaVi_dict[info_list[1]] = summ1
        if info_list[0] == 'Fnatic' :
            summ2 = (int(info_list[2])*2) + int(info_list[3])  + (int(info_list[5])*2) + (int(info_list[6])*3)+ (int(info_list[7])*(-1))
            if summ2 not in Fnatic_dict :
                Fnatic_dict[info_list[1]] = summ2
for value1 in NaVi_dict.values() :
    for value2 in Fnatic_dict.values() :
        if value1 > value2 :
            value_list.append(value1)
        elif value2 > value1 :
            value_list.append(value2)
value_list.sort()
print(value_list)
for val in value_list :
    for key1,value1 in NaVi_dict.items() :
        if val == value1 and key1 not in name_list :
            name_list.append(key1)
    for key2,value2 in Fnatic_dict.items() :
        if val == value2 and key2 not in name_list:
            name_list.append(key2)
print ('First:',name_list[-1])
print('Second:',name_list[-2])
print('Third:',name_list[-3])
#NaVi flamie 23 13 3 2 2 0  = 43

# Fnatic Xizt 15 20 3 2 0 2 = 42

# Fnatic KRIMZ 12 23 9 2 2 1 = 49

# Navi electronic 24 13 5 2 2 0 = 46

# Navi Zeus 14 22 12 2 2 0 = 52

# Navi Edward 20 18 8 1 1 1 = 48

# Fnatic JW 13 24 5 3 0 0 = 45

# Navi s1mple 26 13 6 3 2 1 = 51

# Fnatic twist 25 20 4 2 3 2 = 56

# Fnatic Brollan 14 20 3 2 1 0 = 40
 # First = twist , Second =

5
enter team member informations : NaVi flamia 23 13 3 2 2 0
enter team member informations : Fnatic Xizt 15 20 3 2 0 2
enter team member informations : Fnatic KRIMZ 12 23 9 2 2 1
enter team member informations : NaVi electronic 24 13 5 2 2 0
enter team member informations : NaVi Zeus 14 22 12 2 2 0
[60, 60, 69, 69, 71, 71]
First: electronic
Second: flamia
Third: Zeus

# Question 4
You will be given a String S which contains only two characters - A and B. Your task is to find some substring pattern P in that string. The pattern P is - a substring will contain an equal number of A and B in each side. For example, in AABAABBAA, we get AB, AABB, BA, BBAA. In this problem, you have to print each pattern P present in the string S along with their frequency. Finally, print the largest pattern P. If there are multiple largest patterns, print the one that came first.


Sample Input


AABAABBAA      

Sample Output

AB - 2 times

BA - 2 times

AABB - 1 times

BBAA - 1 times

Longest Pattern - AABB

In [4]:
# task 4 
# word = input(' enter A and B into a word : ')
word = 'AABAABBAA'
ans_dict = {}
ans_list = []
result_list = []
key_len = []
for i in range(0,len(word)-1) :
    a_count = 0
    b_count = 0
    a_word = ''
    new_count = 0
    if word[i] == 'A' :
        a_count += 1 
    if word[i] == 'B' :
        b_count += 1
    if word[i] != word[i+1] and a_count != b_count :
        ans = word[i] + word[i+1]
#         total_count += 1
        if ans not in ans_dict :
            ans_dict[ans] = 1
        else :
            ans_dict[ans] += 1
    elif word[i] == word[i+1] and a_count != b_count :
        ans = word[i] + word[i+1]
        ans_list.append(ans)
for k in range(0,len(ans_list)-1) :
    if ans_list[k] != ans_list[k+1] or ans_list[k+1] != ans_list[k] :
        ans = ans_list[k] + ans_list[k+1]
        if ans not in ans_dict :
            ans_dict[ans] = 1
        else :
            ans_dict[ans] += 1
for key,value in ans_dict.items() :
    print (key,'-',value,'times')
    key_len.append(len(key))
    key_len.sort(reverse = True)
for k in range(len(key_len)) :
    key_count = 0
    for key in ans_dict.keys() :
        if len(key) == key_len[0] :
            key_count += 1 
        if key_count >= 1 :
            ans = key
            break
        else :
            ans = key 
    
print ('Longest patter',ans)

AB - 2 times
BA - 2 times
AABB - 1 times
BBAA - 1 times
Longest patter AABB

# Question 5
Write a program that reads a long sequence of characters and a word of length 3 with unique characters from the user. Then print the number of times the given word can be written from the characters in the given sequence.
Sample input:

Enter Sequence of characters: that is a cat

given word: hat

Sample output:

Number of times ‘hat’ can be written from the given sequence: 1

 
Sample input:

Enter Sequence of characters: Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.

given word: red

Sample output:

Number of times ‘red’ can be written: 6

In [41]:
sentence = "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
# sentence_list = sentence.split(' ')
# sentence = 'that is a cat'
given_word = 'red'
count = 1
ans = ''
ans2 = ''
for word in sentence:
    if word == given_word[0]:
        ans += word
    if word == given_word[1]:
        ans += word
    if word == given_word[2] :
        ans += word
for i in range(0,len(ans)-2) :
    if ans[i] == given_word[0] and ans[i+1] == given_word[1] and ans[i+2] == given_word[2]:
        ans2 = ans[i] + ans[i+1] + ans[i+2]
    if ans2 == given_word :
        count += 1 
print ('Number of times',"'",given_word,"'",'can be written:',count)

Number of times ' red ' can be written: 6

# Question 6
As a software engineer, you are hired to arrange cricket players based on their country and type. You have given all the player’s information in a tuple called my_tuple. The players are from 3 countries which are Bangladesh, Australia and England. They are 2 types which are “Batters” and “Bowlers”


You are given the following nested tuple where each element in the my_tuple is a tuple consisting of a name and a 4 digit ID. 

 
my_tuple = (("Mominul", 1101),("Mustafiz", 1202),("Bell", 2101),("Cook", 2103),("Smith", 3101),("Finch", 3102),("Starc", 3203), ("Imrul", 1103), ("Taijul", 1204))


Write a python program that will convert this tuple into the following dictionary using the process described below: Your code should work for all types of similar tuple if the sample input is changed.


Output dictionary (You just have to print the resultant dictionary. No need to follow the pattern below)

{
'Bangladesh': 

    {
    
    'Batters': ('Mominul', 'Imrul'), 
    
    'Bowlers': ('Mustafiz', 'Taijul')
    
    }, 
    
'England': 

  {
  
   'Batters': ('Bell', 'Cook')
   
   },
'Australia': 
    {
    'Batters': ('Smith', 'Finch'), 
    
    'Bowlers': 'Starc'
    
    }
}


Here you need to convert the given tuple into the output using the 4 digit ID. The rules are given below:
1==> First digit of the ID represents the country. Here
    1a--> 1 means Bangladesh
    1b--> 2 means England
    1c--> 3 Means Australia
2==> Second digit of the ID represents type. Here
    2a--> 1 means Batters
    2b--> 2 means Bowlers
3==> If you have multiple players in a category use tuple to store the multiple names as the value of the nested dictionary
4==> If any type is missing from the country, no need to add that type as key in the nested dictionary (e.g: Bowlers is not present as key in the nested dictionary situated in England key)
5==> If your output dictionary’s key value pair sequence is not the same as the shown output you should not worry about that. However, the key value pair should be exactly the same

In [32]:
my_tuple = (("Mominul", 1101),("Mustafiz", 1202),("Bell", 2101),
            ("Cook", 2103),("Smith", 3101),("Finch", 3102),
            ("Starc", 3203), ("Imrul", 1103), ("Taijul", 1204))
my_dict = {}
dic = {}
batter_list1 = []
bowler_list1 = []
batter_list2 = []
bowler_list2 = []
batter_list3 = []
bowler_list3 = []
name_list = []
for t in my_tuple :
    num = str(t[1])
    if num[0] == '1' :
        my_dict['Bangladesh'] = {'Batters':batter_list1,'Bowlers':bowler_list1}
        if num[1] == '1' :
            batter_list1.append(t[0])
        if num[1] == '2' :
            bowler_list1.append(t[0])

    if num[0] == '2' :
        my_dict['England'] =  {'Batters':batter_list2,'Bowlers':bowler_list2}
        if num[1] == '1' :
            batter_list2.append(t[0])
        if num[1] == '2' :
            bowler_list2.append(t[0])
    
    if num[0] == '3' :
        my_dict['Australia'] = {'Batters':batter_list3,'Bowlers':bowler_list3}
        if num[1] == '1' :
            batter_list3.append(t[0])
        if num[1] == '2' :
            bowler_list3.append(t[0])
print (my_dict)

{'Bangladesh': {'Batters': ['Mominul', 'Imrul'], 'Bowlers': ['Mustafiz', 'Taijul']}, 'England': {'Batters': ['Bell', 'Cook'], 'Bowlers': []}, 'Australia': {'Batters': ['Smith', 'Finch'], 'Bowlers': ['Starc']}}

In [15]:
my_tuple = (("Mominul", 1101),("Mustafiz", 1202),("Bell", 2101),
            ("Cook", 2103),("Smith", 3101),("Finch", 3102),
            ("Starc", 3203), ("Imrul", 1103), ("Taijul", 1204))
country = {'1':'Bangladesh','2':'England','3':'Australia'}
bat_dict = {}
ball_dict = {}
my_dict = {}
for t in my_tuple :
    num = str(t[1])
    name = t[0]
    if num[1] == '1' and num not in bat_dict  :
        bat_dict[num] = name  
    if num[1] == '2' and num not in ball_dict:
        ball_dict[num] = name 
for key1,value1 in country.items() :
    for key2,value2 in bat_dict.items() :
        if key1 == key2[0] and value1 not in my_dict :
            my_dict[value1] = [value2]
        else :
            my_dict[value1].append(value2)
print(bat_dict) 
print(ball_dict)
print(my_dict)

KeyError: 'England'

# Question 7
You are given a list of courses that are currently available in BRACU that looks like the following:
    
   
courses = ['CSE110','CSE111','MAT620','CSE520','EEE361','CSE650','MAT510'].


All courses till 400 level (499) are for the undergraduate students whereas any courses above 500 are for the graduate or masters students.


Write a python program that creates a dictionary from the above list where the keys will be each department name (CSE,EEE,MAT for the above example) and their values will be a dictionary of two keys - 
Undergraduate Courses and Graduate Courses.


Each key will have courses that fall in Undergraduate and Graduate level respectively.



Sample Input - No need to take input


['CSE110','CSE111','MAT620','CSE520','EEE361','CSE650','MAT510']


Sample Output: (You just have to print the resultant dictionary. No need to follow the pattern below)


{

    'CSE':{
    
        'Undergraduate':['CSE110','CSE111'],
        
        'Graduate':['CSE520','CSE650']
        
    },
    
    
    'EEE':{
    
        'Undergraduate':['EEE361'],
        
        'Graduate':[]
        
    },
    
    'MAT':{
    
        'Undergraduate':[],
        
        'Graduate':['MAT510','MAT620']
        
    }   
}

In [15]:
# task 7 
courses = ['CSE110','CSE111','MAT620','CSE520','EEE361','CSE650','MAT510']
courses_dict = {}
dic1= {}
dic2 = {}
dic3 = {}
un_course_list1 = []
grad_course_list1 = []
un_course_list2 = []
grad_course_list2 = []
un_course_list3 = []
grad_course_list3 = []
for i in range(0,len(courses)) :
    name = courses[i][0:3]
    num = courses[i][3:]
    
    if name == 'CSE' :
        courses_dict['CSE'] = {'Undergraduate':un_course_list1,'Graduate':grad_course_list1}  
        if 100 <= int(num) < 500 :
            un_course_list1.append(courses[i])
        if int(num) >= 500 :
            grad_course_list1.append(courses[i])
    if name == 'EEE' :
        courses_dict['EEE'] = {'Undergraduate':un_course_list2,'Graduate':grad_course_list2}
        if 100 <= int(num) < 500 :
            un_course_list2.append(courses[i])  
        if int(num) >= 500 :
            grad_course_list2.append(courses[i])

    if name == 'MAT' :
        courses_dict['MAT'] = {'Undergraduate':un_course_list3,'Graduate':grad_course_list3}
        if 100 <= int(num) < 500 :
            un_course_list3.append(courses[i])
        if int(num) >= 500 :
            grad_course_list3.append(courses[i])
        
    
print(courses_dict)

{'CSE': {'Undergraduate': ['CSE110', 'CSE111'], 'Graduate': ['CSE520', 'CSE650']}, 'MAT': {'Undergraduate': [], 'Graduate': ['MAT620', 'MAT510']}, 'EEE': {'Undergraduate': ['EEE361'], 'Graduate': []}}

# Question 8
An IP address is divided into 4 sections where each section contains 1-3 digits. An example of an IP address would be 192.168.10.3 . Now IP addresses have 2 parts; One is the network part while the other one is the host part. If the network part is 1, we get a special address from the given IP address where the 1st section will remain as it is and the rest of the 3 sections will become 0. If the network part is 2, we get a special address from the given IP address where the first 2 sections will remain as it is and the rest of the 2 sections will become 0. Same goes for other values of the network part. For simplicity we will consider the network part can be 1 or 2 or 3.

Lets see an example:

IP address: 192.168.10.30
If network part = 1 , then special address = 192.0.0.0
If network part = 2 , then special address = 192.168.0.0
If network part = 3 , then special address = 192.168.10.0

All IP addresses starting like the special address will fall under the same special network. You will be given the value of the network part and a list of IP addresses as input. Your task will be to create a dictionary where the keys will be the unique special addresses and the corresponding values will be the list of IP addresses that fall under the same special network.

Input format: Value of network part<Space>List of IP addresses separated by “,”

Sample Input 1:
1 192.168.30.10,168.192.100.30,192.152.55.10,240.169.10.10,168.200.43.90,192.169.100.45

Sample Output 1:
{
“192.0.0.0”: [“192.168.30.10”, “192.152.55.10”, “192.169.100.45”],
“168.0.0.0”: [“168.192.100.30”, “168.200.43.90”],
“240.0.0.0”: [“240.169.10.10”]
}

Sample Input 2:
2 192.168.30.10,168.192.100.30,192.168.55.10,240.169.10.10,168.192.43.90,192.169.100.45

Sample Output 2:
{
“192.168.0.0”: [“192.168.30.10”, “192.168.55.10”],
“168.192.0.0”: [“168.192.100.30”, “168.192.43.90”],
“240.169.0.0”: [“240.169.10.10”]
“192.169.0.0”: [“192.169.100.45”]
}

In [4]:
# task 8 
# address = '1 192.168.30.10,168.192.100.30,192.152.55.10,240.169.10.10,168.200.43.90,192.169.100.45'
address = '2 192.168.30.10,168.192.100.30,192.168.55.10,240.169.10.10,168.192.43.90,192.169.100.45'
network = address[0]
host = address[2:]
host_list = host.split(',')
my_dict = {}
count = 0
for i in range(0,len(host_list)-1) :
    print(host_list[i])
    new_list = host_list[i].split('.')
    if network == '1' :
        ans1 = new_list[1] = '0'
        ans2 = new_list[2] = '0'
        ans3 = new_list[3] = '0'
        ans = new_list[0] + '.' + ans1 + '.' + ans2 + '.' + ans3
    elif network == '2' :
        ans1 = new_list[2] = '0'
        ans2 = new_list[3] = '0'
        ans = new_list[0] + '.' + new_list[1] + '.' + ans1 + '.' + ans2
    elif network == '3' :
        ans1 = new_list[3] = '0'
        ans = new_list[0] + '.' + new_list[1] + '.' + new_list[2] + '.' + ans1
    if network == '1' :
        if ans[:3] == new_list[0]  :
            my_dict[ans] = [host_list[i]]
            count += 1
        if count >= 1 :
            my_dict[ans].append(host_list[i])
    elif network == '2' :
        if ans[:3] == new_list[0] or ans[4:7]  == new_list[1]:
            my_dict[ans] = [host_list[i]]
            count += 1
        if count >= 1 :
            my_dict[ans].append(host_list[i])
    
print(my_dict)

192.168.30.10
168.192.100.30
192.168.55.10
240.169.10.10
168.192.43.90
{'192.168.0.0': ['192.168.55.10', '192.168.55.10'], '168.192.0.0': ['168.192.43.90', '168.192.43.90'], '240.169.0.0': ['240.169.10.10', '240.169.10.10']}

In [59]:
inp = 'Bob 01632342392 Alice 01346734123'.split()
print(inp)
key = ''
value = ''
dic = {}
z = 0
ans = ''
for i in range(0,len(inp)-1) :
    if inp[i]  not in dic :
        dic[inp[i]] = inp[i+1]
for key,value in dic.items() :
    for k in key :
        if k in '1,2,3,4,5,6,7,8,9,0' :
            ans += k 
    if ans == key :
        continue 
    else :
        print (key,value)

['Bob', '01632342392', 'Alice', '01346734123']
Bob 01632342392
Alice 01346734123

In [4]:
inp = 'Bob 01632342392 Alice 01346734123 Britney 01803544535 Aeron 01723454642 Smith 01923457890 Tarek 01866392233'
inp_list = inp.split(' ')
name_list = []
num_list = []
dic = {}
new_dic = {}
dic1 = {}
dic2 = {}
dic3 = {}
dic4 ={}
for i in range(0,len(inp_list),2) :
    name_list.append(inp_list[i])
for j in range(1,len(inp_list),2) :
    num_list.append(inp_list[j])
for k in range(len(name_list)):
    for p in range(len(num_list)) :
        if k == p :
            dic[name_list[k]] = num_list[p]
print (dic)
for key,value in dic.items() :
    if value[:3] == '016' :
        new_dic['Airtel'] = dic1
        dic1[key] = value 
    elif value[:3] == '017' or value[:3] == '013' :
        new_dic['Grameenphone'] = dic2
        dic2[key] = value
    elif value[:3] == '018' :
        new_dic['Robi'] = dic3 
        dic3[key] = value 
    elif value[:3] != '016' or value[:3] != '013' or value[:3] != '017' or value[:3] != '016':
        new_dic['Others'] = dic4 
        dic4[key] = value 
print(new_dic)

{'Bob': '01632342392', 'Alice': '01346734123', 'Britney': '01803544535', 'Aeron': '01723454642', 'Smith': '01923457890', 'Tarek': '01866392233'}
{'Airtel': {'Bob': '01632342392'}, 'Grameenphone': {'Alice': '01346734123', 'Aeron': '01723454642'}, 'Robi': {'Britney': '01803544535', 'Tarek': '01866392233'}, 'Others': {'Smith': '01923457890'}}